version: "3.3"
services: 
    api:
        build: 
            context: ./setup/api
            dockerfile: Dockerfile
        image: edu.carvaans.api
        volumes: 
            -   ./api:/app:rw
            -   ./setup/api/nginx.conf:/usr/share/nginx/nginx.conf:ro
        working_dir: /app
        container_name: edu.carvaans.api
        ports: 
            -   "5000:80"
        networks: 
            carvaan-networks:
                ipv4_address: 173.20.1.2
        tty: "true"
        command: ["nginx"]
        depends_on: 
            -   php
    php:
        build: 
            context: ./setup/api
            dockerfile: Dockerfile-PHP.dockerfile
        image: edu.carvaans.php
        volumes: 
            -   ./api:/app:rw
        working_dir: /app
        container_name: edu.carvaans.php
        ports: 
            -   "9000"
        networks: 
            carvaan-networks:
                ipv4_address: 173.20.1.3
        tty: "true"
    # app:
    #     build: ./setup/app
    #     container_name: edu.carvaans.app
    #     tty: "true"
    #     ports: 
    #         -   "5001:80"
    #     networks: 
    #         carvaan-networks:
    #             ipv4_address: 173.20.1.11
    #     volumes: 
    #         -   ./setup/api/default.conf:/etc/nginx/conf.d/default.conf
    #     depends_on: 
    #         -   cache
    #         -   db
    # cache:
    #     build: ./setup/redis
    #     container_name: edu.carvaans.cache
    #     tty: "true"
    #     ports: 
    #         -   "5002:6379"
    #     networks: 
    #         carvaan-networks:
    #             ipv4_address: 173.20.1.12
    # db:
    #     build: ./setup/db
    #     container_name: edu.carvaans.db
    #     tty: "true"
    #     ports: 
    #         -   "5003:5432"
    #     networks: 
    #         carvaan-networks:
    #             ipv4_address: 173.20.1.13

networks: 
    carvaan-networks:
        ipam: 
            driver: default
            config: 
                -   subnet: 173.20.1.0/10